name: Build Desktop App
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Install Nativefier
        run: npm install -g nativefier
      
      - name: Build Windows App
        run: nativefier --name "GhazaliApp" "https://salmsalm77kd-ux.github.io/ghazali-app/" ./build-out/
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Windows-EXE-App
          path: ./build-out/
